### PR TITLE
mahi#19 mahi v1 crash on bad role mgmt log entry

### PR DESCRIPTION
**Pull request by arekinath**
testing done:
 * patched into production installation to stop it from crashing
 * ran `make check`
   - it fails in the copyright check, but I have no right to update a joyent copyright line

### CODE REVIEW

**Review by danmcd — COMMENTED** [review]
Put "Copyright Alex WIlson" or your Uni if you're bound by contract to include them.  Fix that, and I'll approve/pull.

**Comment by danmcd** [comment]
Ooh, I may also file a TRITON ticket for it.

**Comment by bahamat** [comment]
@arekinath To be clear, this fix will make it "truck on"?

**Comment by arekinath** [comment]
Yes, this will make it "truck on", as it already will in the case where there are any other group/role memberships left. As a result, it may mean that the user stays in a group in mahi which they're not a member of in UFDS (already happens in other cases, too). This can be rectified later by re-adding the user to the role and removing them again -- with more time between the two actions to make sure it syncs to the log.

**Review by danmcd — APPROVED** [review]

**Comment by danmcd** [comment]
Moving this to #21 so we can unleash our Jenkins w/o your help, @arekinath .

**Comment by danmcd** [comment]
Pushed manually to preserve author information.

**Pull request closed without merging**
